### PR TITLE
Create Osso .travis.yml

### PR DESCRIPTION
**Pull request by m0j0hn**
Create a .travis.yml file so Osso can build on Travis CI

### CODE REVIEW

**Comment by m0j0hn** [comment]
Obviously these commits should be squashed

**Comment by joey** [comment]
This looks good to me. I submitted a request for travis to have access to this repo which is also required. IIRC, that will also kick off a build of this branch to make sure that the integration is working correctly before merging to master. Thanks @m0j0hn!

**Comment by esammer** [comment]
I approved the Travis CI request. You should be good to go.

**Comment by joey** [comment]
Thanks @esammer! @m0j0hn I'm going to squash and merge this now. Thanks for the contribution!

**Pull request merged**
